version: '3'

volumes:
  django_neo4j_local_postgres_data: {}
  django_neo4j_local_postgres_data_backups: {}
  django_neo4j_local_neo4j_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_neo4j_local_django
    container_name: django_neo4j_local_django
    depends_on:
      - postgres
      - neo4j
      - redis
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: django_neo4j_production_postgres
    container_name: django_neo4j_local_postgres
    volumes:
      - django_neo4j_local_postgres_data:/var/lib/postgresql/data
      - django_neo4j_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  neo4j:
    image: neo4j:5.9.0
    container_name: django_neo4j_local_neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - django_neo4j_local_neo4j_data:/data
    environment:
      # Raise memory limits
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_server_memory_heap_max__size=1G

  docs:
    image: django_neo4j_local_docs
    container_name: django_neo4j_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./django_neo4j:/app/django_neo4j:z
    ports:
      - '9000:9000'
    command: /start-docs

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: django_neo4j_local_mailhog
    ports:
      - '8025:8025'

  redis:
    image: redis:6
    container_name: django_neo4j_local_redis

  celeryworker:
    <<: *django
    image: django_neo4j_local_celeryworker
    container_name: django_neo4j_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: django_neo4j_local_celerybeat
    container_name: django_neo4j_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: django_neo4j_local_flower
    container_name: django_neo4j_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: django_neo4j_local_node
    container_name: django_neo4j_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - '3000:3000'
